include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    avoid_relative_lib_imports: true
    avoid_init_to_null: true
    slash_for_doc_comments: true
    public_member_api_docs: false
    avoid_catches_without_on_clauses: false