name: frontend
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  draggable_flutter_list: ^1.0.3
  flutter:
    sdk: flutter
  # State Management
  graphql_flutter: ^5.0.0-nullsafety.1
  provider: ^5.0.0
  # Remote
  data_connection_checker: ^0.3.4
  graphql: 
  # Local
  shared_preferences: ^2.0.5
  flutter_secure_storage:
  sqflite: ^1.3.0
  # fp
  either_option: ^1.0.6
  #auth
  jwt_decoder: ^2.0.0
  email_validator: '^1.0.6'
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
  lint:
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/images/coffee-icon.png
    - assets/images/stocks.png
    - assets/images/orders.png
    - assets/images/Xpos.png
  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: "assets/fonts/montserrat.ttf"
