name: frontend
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  draggable_flutter_list: ^1.0.3
  flutter:
    sdk: flutter

  # State Management
  graphql_flutter: ^5.0.0-nullsafety.1
  provider: ^5.0.0

  # Remote
  data_connection_checker: ^0.3.4
  connectivity: ^3.0.6
  graphql: 

  # Local
  shared_preferences: ^2.0.5
  flutter_secure_storage:
  sqflite: 
  moor_flutter:

  # fp
  either_option: ^1.0.6

  #auth
  jwt_decoder: ^2.0.0
  email_validator: '^1.0.6'
  cupertino_icons: ^1.0.2

  #SMS
  flutter_sms: ^2.3.1

  # Charts
  graphic: ^0.3.0
  
  #Photo Storage
  firebase_storage: ^8.0.5
  firebase_core: ^1.1.0
  image_picker: ^0.7.4
  cached_network_image: ^3.0.0
  
  #PDF
  pdf: ^3.3.0
  open_file: ^3.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
  moor_generator:
  build_runner:
  lint:
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/images/coffee-icon.png
    - assets/images/stocks.png
    - assets/images/orders.png
    - assets/images/Xpos.png
    - assets/images/xpos_home_logo.png
    - assets/images/stocks.png
    - assets/images/sample.png
    - assets/images/cappuccino.jpg
    - assets/images/loading.jpg
    - assets/images/loading.gif
    - assets/images/processorders.png
    - assets/images/inventory.png
    - assets/images/discount.png
    - assets/images/taxes.png
    - assets/images/user.png
    - assets/images/empty_orders.png
    - assets/images/blue_added.png
    - assets/images/blue_edited.png
    - assets/images/empty_inventory.png

  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: "assets/fonts/montserrat.ttf"
    - family: Montserrat
      fonts:
        - asset: "assets/fonts/montserrat_reg.ttf"
    - family: Montserrat Superbold
      fonts:
        - asset: "assets/fonts/montserrat_superbold.ttf"
